use std::fs;
use std::path::Path;

#[derive(Debug)]
pub struct GenerateConfig {
    pub project_name: String,
    pub template_id: String,
    pub frontend: String,
    pub backend: String,
    pub database: String,
}

#[derive(Debug)]
pub struct GenerateResult {
    pub folders: Vec<String>,
    pub files: Vec<String>,
}

pub fn folder_exists(project_name: &str) -> bool {
    Path::new(project_name).exists()
}

pub fn generate(config: &GenerateConfig) -> Result<GenerateResult, String> {
    if config.project_name.is_empty() {
        return Err("Project name cannot be empty".to_string());
    }

    let root = Path::new(&config.project_name);
    let mut result = GenerateResult { folders: Vec::new(), files: Vec::new() };

    // Create root directory (overwrite if exists)
    if root.exists() {
        fs::remove_dir_all(root).map_err(|e| e.to_string())?;
    }
    fs::create_dir_all(root).map_err(|e| e.to_string())?;

    // Get template folders
    let template_folders = crate::template::TemplateRegistry::get(&config.template_id)
        .map(|t| t.structure.folders.clone())
        .unwrap_or_default();

    // Get stack folders
    let frontend_folders = crate::stack::get_frontend_folders(&config.frontend)
        .unwrap_or(&[])
        .to_vec();
    let backend_folders = crate::stack::get_backend_folders(&config.backend)
        .unwrap_or(&[])
        .to_vec();

    // Create template-specific folders
    for folder in &template_folders {
        let path = root.join(folder);
        fs::create_dir_all(&path).map_err(|e| e.to_string())?;
        result.folders.push(folder.to_string());
    }

    // Generate template-specific files
    if let Some(template) = crate::template::TemplateRegistry::get(&config.template_id) {
        for file in &template.structure.files {
            let path = root.join(&file.path);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            let content = template_file_content(&file.template_source);
            fs::write(&path, content).map_err(|e| e.to_string())?;
            result.files.push(file.path.clone());
        }
    }

    // Create frontend folders and files
    if config.frontend != "none" {
        let frontend_root = root.join("frontend/");
        for folder in &frontend_folders {
            let path = frontend_root.join(folder);
            fs::create_dir_all(&path).map_err(|e| e.to_string())?;
            result.folders.push(format!("frontend/{}", folder));
        }

        // Generate frontend files
        if let Some(files) = crate::stack::get_frontend_files(&config.frontend) {
            for file in files {
                let path = frontend_root.join(file.path);
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).map_err(|e| e.to_string())?;
                }
                fs::write(&path, file.content).map_err(|e| e.to_string())?;
                result.files.push(format!("frontend/{}", file.path));
            }
        }
    }

    // Create backend folders and files
    if config.backend != "none" {
        let backend_root = root.join("backend/");
        for folder in &backend_folders {
            let path = backend_root.join(folder);
            fs::create_dir_all(&path).map_err(|e| e.to_string())?;
            result.folders.push(format!("backend/{}", folder));
        }

        // Generate backend files
        if let Some(files) = crate::stack::get_backend_files(&config.backend) {
            for file in files {
                let path = backend_root.join(file.path);
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).map_err(|e| e.to_string())?;
                }
                fs::write(&path, file.content).map_err(|e| e.to_string())?;
                result.files.push(format!("backend/{}", file.path));
            }
        }
    }

    // Generate security config files
    fs::write(root.join(".env.example"), env_example_content(&config.database))
        .map_err(|e| e.to_string())?;
    result.files.push(".env.example".to_string());

    fs::write(root.join(".gitignore"), gitignore_content())
        .map_err(|e| e.to_string())?;
    result.files.push(".gitignore".to_string());

    // Generate README with install commands
    fs::write(root.join("README.md"), readme_content(config))
        .map_err(|e| e.to_string())?;
    result.files.push("README.md".to_string());

    Ok(result)
}

fn env_example_content(database: &str) -> String {
    let db_url = crate::stack::get_database_url(database);
    format!(r#"# Database
DATABASE_URL={}

# API
API_PORT=3000
API_SECRET=your-secret-here

# Security
CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_WINDOW=60000
RATE_LIMIT_MAX=100

# [GENERATED BY SNIPE-CODE CLI]
"#, db_url)
}

fn gitignore_content() -> &'static str {
    r#"# Dependencies
node_modules/
target/
vendor/
vendor/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Build
dist/
build/
out/
"#
}

fn readme_content(config: &GenerateConfig) -> String {
    let mut sections = Vec::new();

    sections.push(format!("# {}\n", config.project_name));
    sections.push("Generated by SNIPE-CODE CLI\n".to_string());

    // Frontend setup
    if config.frontend != "none" {
        let fe_name = crate::stack::FRONTEND_STACKS.iter()
            .find(|s| s.id == config.frontend)
            .map(|s| s.name)
            .unwrap_or("Frontend");
        let init_cmd = crate::stack::get_frontend_init_command(&config.frontend);
        let install_cmd = crate::stack::get_frontend_install_command(&config.frontend);

        sections.push("## Frontend Setup\n".to_string());
        sections.push(format!("Stack: {}\n", fe_name));
        if !init_cmd.is_empty() {
            sections.push(format!("```bash\ncd frontend\n{}\n{}\n```\n", init_cmd, install_cmd));
        }
    }

    // Backend setup
    if config.backend != "none" {
        let be_name = crate::stack::BACKEND_STACKS.iter()
            .find(|s| s.id == config.backend)
            .map(|s| s.name)
            .unwrap_or("Backend");
        let init_cmd = crate::stack::get_backend_init_command(&config.backend);
        let install_cmd = crate::stack::get_backend_install_command(&config.backend);

        sections.push("## Backend Setup\n".to_string());
        sections.push(format!("Stack: {}\n", be_name));
        if !init_cmd.is_empty() {
            sections.push(format!("```bash\ncd backend\n{}\n{}\n```\n", init_cmd, install_cmd));
        }
    }

    sections.join("\n")
}

fn template_file_content(template_source: &str) -> String {
    match template_source {
        "portfolio-projects" => {
            r#"{
  "projects": [
    {
      "title": "Project Name",
      "description": "Brief description of the project",
      "image": "/images/project.png",
      "tags": ["React", "TypeScript"],
      "link": "https://github.com/..."
    }
  ]
}"#.to_string()
        }
        "blog-sample-post" => {
            r#"---
title: "Hello World"
date: "2026-07-28"
tags: ["rust", "cli"]
category: "tutorial"
author: "SNIPE-CODE Team"
---

# Hello World

Welcome to your new blog! This is a sample post to get you started.

## Getting Started

Edit this file or create new `.mdx` files in the `posts/` directory.

## Features

- Markdown/MDX support
- Automatic RSS feed
- Categories and tags
- Responsive design
"#.to_string()
        }
        "blog-rss-feed" => {
            r#"<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>My Blog</title>
    <description>Generated by SNIPE-CODE CLI</description>
    <link>http://localhost:3000</link>
    <atom:link href="http://localhost:3000/rss.xml" rel="self" type="application/rss+xml"/>
    <item>
      <title>Hello World</title>
      <link>http://localhost:3000/posts/hello-world</link>
      <pubDate>Wed, 28 Jul 2026 00:00:00 GMT</pubDate>
      <description>Welcome to your new blog!</description>
    </item>
  </channel>
</rss>
"#.to_string()
        }
        _ => String::new(),
    }
}

pub fn dry_run_preview(config: &GenerateConfig) -> String {
    if config.project_name.is_empty() {
        return "Error: project name empty".to_string();
    }

    let mut entries: Vec<String> = Vec::new();

    // Check if folder exists
    let root = Path::new(&config.project_name);
    if root.exists() {
        entries.push("[WARNING] Folder already exists — will be overwritten".to_string());
    }

    // Collect template folders
    let template_folders = crate::template::TemplateRegistry::get(&config.template_id)
        .map(|t| t.structure.folders.clone())
        .unwrap_or_default();
    for f in &template_folders {
        entries.push(f.clone());
    }

    // Collect template files
    if let Some(template) = crate::template::TemplateRegistry::get(&config.template_id) {
        for file in &template.structure.files {
            entries.push(file.path.clone());
        }
    }

    // Collect frontend folders
    if config.frontend != "none" {
        let fe_folders = crate::stack::get_frontend_folders(&config.frontend)
            .unwrap_or(&[])
            .to_vec();
        for f in fe_folders {
            entries.push(format!("frontend/{}", f));
        }

        // Add frontend files
        if let Some(files) = crate::stack::get_frontend_files(&config.frontend) {
            for file in files {
                entries.push(format!("frontend/{}", file.path));
            }
        }
    }

    // Collect backend folders
    if config.backend != "none" {
        let be_folders = crate::stack::get_backend_folders(&config.backend)
            .unwrap_or(&[])
            .to_vec();
        for f in be_folders {
            entries.push(format!("backend/{}", f));
        }

        // Add backend files
        if let Some(files) = crate::stack::get_backend_files(&config.backend) {
            for file in files {
                entries.push(format!("backend/{}", file.path));
            }
        }
    }

    // Add root files
    entries.push(".env.example".to_string());
    entries.push(".gitignore".to_string());
    entries.push("README.md".to_string());

    format_tree(&config.project_name, &entries)
}

fn format_tree(project_name: &str, entries: &[String]) -> String {
    let mut lines = Vec::new();
    lines.push(format!("{}/", project_name));

    let total = entries.len();
    for (i, entry) in entries.iter().enumerate() {
        let is_last = i == total - 1;
        let connector = if is_last { "└── " } else { "├── " };
        lines.push(format!("{}{}{}", connector, entry, ""));
    }

    lines.push(String::new());
    lines.push("(0 files created — dry run mode)".to_string());

    lines.join("\n")
}
