use std::fs;
use std::path::Path;

#[derive(Debug)]
pub struct GenerateConfig {
    pub project_name: String,
    pub template_id: String,
    pub frontend: String,
    pub backend: String,
    pub database: String,
}

#[derive(Debug)]
pub struct GenerateResult {
    pub folders: Vec<String>,
    pub files: Vec<String>,
}

pub fn generate(config: &GenerateConfig) -> Result<GenerateResult, String> {
    if config.project_name.is_empty() {
        return Err("Project name cannot be empty".to_string());
    }

    let root = Path::new(&config.project_name);
    let mut result = GenerateResult { folders: Vec::new(), files: Vec::new() };

    // Create root directory
    fs::create_dir_all(root).map_err(|e| e.to_string())?;

    // Get template folders
    let template_folders = crate::template::TemplateRegistry::get(&config.template_id)
        .map(|t| t.structure.folders.clone())
        .unwrap_or_default();

    // Get stack folders
    let frontend_folders = crate::stack::get_frontend_folders(&config.frontend)
        .unwrap_or(&[])
        .to_vec();
    let backend_folders = crate::stack::get_backend_folders(&config.backend)
        .unwrap_or(&[])
        .to_vec();

    // Create template-specific folders
    for folder in &template_folders {
        let path = root.join(folder);
        fs::create_dir_all(&path).map_err(|e| e.to_string())?;
        result.folders.push(folder.to_string());
    }

    // Create frontend folders
    if config.frontend != "none" {
        let frontend_root = root.join("frontend/");
        for folder in &frontend_folders {
            let path = frontend_root.join(folder);
            fs::create_dir_all(&path).map_err(|e| e.to_string())?;
            result.folders.push(format!("frontend/{}", folder));
        }
    }

    // Create backend folders
    if config.backend != "none" {
        let backend_root = root.join("backend/");
        for folder in &backend_folders {
            let path = backend_root.join(folder);
            fs::create_dir_all(&path).map_err(|e| e.to_string())?;
            result.folders.push(format!("backend/{}", folder));
        }
    }

    // Generate security config files
    fs::write(root.join(".env.example"), env_example_content())
        .map_err(|e| e.to_string())?;
    result.files.push(".env.example".to_string());

    fs::write(root.join(".gitignore"), gitignore_content())
        .map_err(|e| e.to_string())?;
    result.files.push(".gitignore".to_string());

    // Generate README
    fs::write(root.join("README.md"), readme_content(&config.project_name))
        .map_err(|e| e.to_string())?;
    result.files.push("README.md".to_string());

    // Generate template-specific files
    if config.template_id == "company-profile" {
        let pages = ["home", "about", "services", "contact", "team"];
        for page in &pages {
            let path = root.join(format!("frontend/src/pages/{}/index.html", page));
            fs::write(&path, company_profile_page(page, &config.project_name))
                .map_err(|e| e.to_string())?;
            result.files.push(format!("frontend/src/pages/{}/index.html", page));
        }

        // Layout components
        let header_path = root.join("frontend/src/components/layout/header/Header.tsx");
        fs::write(&header_path, company_profile_header())
            .map_err(|e| e.to_string())?;
        result.files.push("frontend/src/components/layout/header/Header.tsx".to_string());

        let footer_path = root.join("frontend/src/components/layout/footer/Footer.tsx");
        fs::write(&footer_path, company_profile_footer())
            .map_err(|e| e.to_string())?;
        result.files.push("frontend/src/components/layout/footer/Footer.tsx".to_string());
    }

    Ok(result)
}

fn env_example_content() -> &'static str {
    r#"# Database
DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# API
API_PORT=3000
API_SECRET=your-secret-here

# Security
CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_WINDOW=60000
RATE_LIMIT_MAX=100

# [GENERATED BY SNIPE-CODE CLI]
"#
}

fn gitignore_content() -> &'static str {
    r#"# Dependencies
node_modules/
target/
vendor/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Build
dist/
build/
out/
"#
}

fn readme_content(name: &str) -> String {
    format!("# {}\n\nGenerated by SNIPE-CODE CLI\n", name)
}

fn company_profile_page(page: &str, project_name: &str) -> String {
    let (title, description) = match page {
        "home" => ("Home", "Welcome to our company"),
        "about" => ("About Us", "Learn more about our story"),
        "services" => ("Services", "What we offer"),
        "contact" => ("Contact", "Get in touch with us"),
        "team" => ("Our Team", "Meet the people behind the company"),
        _ => (page, "Company profile page"),
    };

    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | {project_name}</title>
    <meta name="description" content="{description}">
    <meta property="og:title" content="{title} | {project_name}">
    <meta property="og:description" content="{description}">
    <meta property="og:type" content="website">
    <script type="application/ld+json">
    {{
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": "{title}",
        "description": "{description}"
    }}
    </script>
</head>
<body>
    <h1>{title}</h1>
    <p>{description}</p>
</body>
</html>
"#)
}

fn company_profile_header() -> &'static str {
    r#"export default function Header() {
    return (
        <header>
            <nav>
                <a href="/">Home</a>
                <a href="/about">About</a>
                <a href="/services">Services</a>
                <a href="/team">Team</a>
                <a href="/contact">Contact</a>
            </nav>
        </header>
    );
}
"#
}

fn company_profile_footer() -> &'static str {
    r#"export default function Footer() {
    return (
        <footer>
            <p>&copy; 2024 Company. All rights reserved.</p>
        </footer>
    );
}
"#
}

pub fn dry_run_preview(config: &GenerateConfig) -> String {
    if config.project_name.is_empty() {
        return "Error: project name empty".to_string();
    }

    let mut entries: Vec<String> = Vec::new();

    // Collect template folders
    let template_folders = crate::template::TemplateRegistry::get(&config.template_id)
        .map(|t| t.structure.folders.clone())
        .unwrap_or_default();
    for f in &template_folders {
        entries.push(f.clone());
    }

    // Collect frontend folders
    if config.frontend != "none" {
        let fe_folders = crate::stack::get_frontend_folders(&config.frontend)
            .unwrap_or(&[])
            .to_vec();
        for f in fe_folders {
            entries.push(format!("frontend/{}", f));
        }
    }

    // Collect backend folders
    if config.backend != "none" {
        let be_folders = crate::stack::get_backend_folders(&config.backend)
            .unwrap_or(&[])
            .to_vec();
        for f in be_folders {
            entries.push(format!("backend/{}", f));
        }
    }

    // Add root files
    entries.push(".env.example".to_string());
    entries.push(".gitignore".to_string());
    entries.push("README.md".to_string());

    // Add template-specific files
    if config.template_id == "company-profile" {
        let pages = ["home", "about", "services", "contact", "team"];
        for page in &pages {
            entries.push(format!("frontend/src/pages/{}/index.html", page));
        }
        entries.push("frontend/src/components/layout/header/Header.tsx".to_string());
        entries.push("frontend/src/components/layout/footer/Footer.tsx".to_string());
    }

    format_tree(&config.project_name, &entries)
}

fn format_tree(project_name: &str, entries: &[String]) -> String {
    let mut lines = Vec::new();
    lines.push(format!("{}/", project_name));

    let total = entries.len();
    for (i, entry) in entries.iter().enumerate() {
        let is_last = i == total - 1;
        let connector = if is_last { "└── " } else { "├── " };
        lines.push(format!("{}{}{}", connector, entry, ""));
    }

    lines.push(String::new());
    lines.push("(0 files created — dry run mode)".to_string());

    lines.join("\n")
}
