use std::fs;
use std::path::Path;

#[derive(Debug)]
pub struct GenerateConfig {
    pub project_name: String,
    pub template_id: String,
    pub frontend: String,
    pub backend: String,
    pub database: String,
}

#[derive(Debug)]
pub struct GenerateResult {
    pub folders: Vec<String>,
    pub files: Vec<String>,
}

pub fn generate(config: &GenerateConfig) -> Result<GenerateResult, String> {
    if config.project_name.is_empty() {
        return Err("Project name cannot be empty".to_string());
    }

    let root = Path::new(&config.project_name);
    let mut result = GenerateResult { folders: Vec::new(), files: Vec::new() };

    // Create root directory
    fs::create_dir_all(root).map_err(|e| e.to_string())?;

    // Get template folders
    let template_folders = crate::template::TemplateRegistry::get(&config.template_id)
        .map(|t| t.structure.folders.clone())
        .unwrap_or_default();

    // Get stack folders
    let frontend_folders = crate::stack::get_frontend_folders(&config.frontend)
        .unwrap_or(&[])
        .to_vec();
    let backend_folders = crate::stack::get_backend_folders(&config.backend)
        .unwrap_or(&[])
        .to_vec();

    // Create template-specific folders
    for folder in &template_folders {
        let path = root.join(folder);
        fs::create_dir_all(&path).map_err(|e| e.to_string())?;
        result.folders.push(folder.to_string());
    }

    // Create frontend folders
    if config.frontend != "none" {
        let frontend_root = root.join("frontend/");
        for folder in &frontend_folders {
            let path = frontend_root.join(folder);
            fs::create_dir_all(&path).map_err(|e| e.to_string())?;
            result.folders.push(format!("frontend/{}", folder));
        }
    }

    // Create backend folders
    if config.backend != "none" {
        let backend_root = root.join("backend/");
        for folder in &backend_folders {
            let path = backend_root.join(folder);
            fs::create_dir_all(&path).map_err(|e| e.to_string())?;
            result.folders.push(format!("backend/{}", folder));
        }
    }

    // Generate security config files
    fs::write(root.join(".env.example"), env_example_content())
        .map_err(|e| e.to_string())?;
    result.files.push(".env.example".to_string());

    fs::write(root.join(".gitignore"), gitignore_content())
        .map_err(|e| e.to_string())?;
    result.files.push(".gitignore".to_string());

    // Generate README
    fs::write(root.join("README.md"), readme_content(&config.project_name))
        .map_err(|e| e.to_string())?;
    result.files.push("README.md".to_string());

    Ok(result)
}

fn env_example_content() -> &'static str {
    r#"# Database
DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# API
API_PORT=3000
API_SECRET=your-secret-here

# Security
CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_WINDOW=60000
RATE_LIMIT_MAX=100

# [GENERATED BY SNIPE-CODE CLI]
"#
}

fn gitignore_content() -> &'static str {
    r#"# Dependencies
node_modules/
target/
vendor/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Build
dist/
build/
out/
"#
}

fn readme_content(name: &str) -> String {
    format!("# {}\n\nGenerated by SNIPE-CODE CLI\n", name)
}
