#[derive(Debug, PartialEq)]
pub struct StackOption {
    pub id: &'static str,
    pub name: &'static str,
    pub folders: &'static [&'static str],
    pub files: &'static [FileDef],
    pub init_command: &'static str,
    pub install_command: &'static str,
}

#[derive(Debug, PartialEq)]
pub struct FileDef {
    pub path: &'static str,
    pub content: &'static str,
}

pub const FRONTEND_STACKS: &[StackOption] = &[
    StackOption {
        id: "nextjs",
        name: "Next.js",
        folders: &["src/components/ui/", "src/components/layout/", "src/app/", "src/hooks/", "src/lib/"],
        files: &[
            FileDef { path: "package.json", content: r#"{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "typescript": "^5.0.0"
  }
}"# },
            FileDef { path: "tsconfig.json", content: r#"{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}"# },
            FileDef { path: "next.config.js", content: "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\n\nmodule.exports = nextConfig;\n" },
            FileDef { path: "src/app/layout.tsx", content: "export const metadata = {\n  title: 'App',\n  description: 'Generated by SNIPE-CODE CLI',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n" },
            FileDef { path: "src/app/page.tsx", content: "export default function Home() {\n  return <main><h1>Welcome</h1></main>;\n}\n" },
        ],
        init_command: "npm init -y",
        install_command: "npm install",
    },
    StackOption {
        id: "react-vite",
        name: "React (Vite)",
        folders: &["src/components/ui/", "src/components/layout/", "src/pages/", "src/hooks/", "src/lib/"],
        files: &[
            FileDef { path: "package.json", content: r#"{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^4.0.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.0"
  }
}"# },
            FileDef { path: "vite.config.ts", content: "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n" },
            FileDef { path: "tsconfig.json", content: r#"{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}"# },
            FileDef { path: "src/App.tsx", content: "function App() {\n  return <div><h1>Welcome</h1></div>;\n}\n\nexport default App;\n" },
            FileDef { path: "src/main.tsx", content: "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n" },
        ],
        init_command: "npm init -y",
        install_command: "npm install",
    },
    StackOption {
        id: "vue",
        name: "Vue",
        folders: &["src/components/ui/", "src/components/layout/", "src/views/", "src/composables/", "src/lib/"],
        files: &[
            FileDef { path: "package.json", content: r#"{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.0",
    "vue-tsc": "^1.0.0"
  }
}"# },
            FileDef { path: "vite.config.ts", content: "import { defineConfig } from 'vite';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({\n  plugins: [vue()],\n});\n" },
            FileDef { path: "tsconfig.json", content: r#"{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
  "references": [{ "path": "./tsconfig.node.json" }]
}"# },
            FileDef { path: "src/App.vue", content: "<script setup lang=\"ts\">\n</script>\n\n<template>\n  <div>\n    <h1>Welcome</h1>\n  </div>\n</template>\n" },
            FileDef { path: "src/main.ts", content: "import { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).mount('#app');\n" },
        ],
        init_command: "npm init -y",
        install_command: "npm install",
    },
    StackOption {
        id: "nuxtjs",
        name: "Nuxt.js",
        folders: &["src/components/ui/", "src/components/layout/", "src/pages/", "src/composables/", "src/lib/"],
        files: &[
            FileDef { path: "package.json", content: r#"{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.10.0",
    "vue": "^3.4.0",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0"
  }
}"# },
            FileDef { path: "nuxt.config.ts", content: "// https://nuxt.com/docs/api/configuration/nuxt-config\nexport default defineNuxtConfig({\n  devtools: { enabled: true },\n});\n" },
            FileDef { path: "tsconfig.json", content: r#"{
  "extends": "./.nuxt/tsconfig.json"
}"# },
            FileDef { path: "app.vue", content: "<template>\n  <div>\n    <NuxtPage />\n  </div>\n</template>\n" },
            FileDef { path: "src/pages/index.vue", content: "<script setup lang=\"ts\">\n</script>\n\n<template>\n  <div>\n    <h1>Welcome</h1>\n  </div>\n</template>\n" },
        ],
        init_command: "npm init -y",
        install_command: "npm install",
    },
    StackOption {
        id: "none",
        name: "None",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
];

pub const BACKEND_STACKS: &[StackOption] = &[
    StackOption {
        id: "dotnet8",
        name: ".NET 8",
        folders: &["src/Controllers/", "src/Services/", "src/Repositories/", "src/Middleware/", "src/Models/"],
        files: &[
            FileDef { path: "app.csproj", content: r#"<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>"# },
            FileDef { path: "Program.cs", content: "var builder = WebApplication.CreateBuilder(args);\n\n// Add services to the container.\nbuilder.Services.AddControllers();\n\nvar app = builder.Build();\n\napp.MapControllers();\n\napp.Run();\n" },
        ],
        init_command: "dotnet new webapi",
        install_command: "dotnet restore",
    },
    StackOption {
        id: "nestjs",
        name: "NestJS",
        folders: &["src/controllers/", "src/services/", "src/repositories/", "src/middleware/", "src/routes/"],
        files: &[
            FileDef { path: "package.json", content: r#"{
  "name": "backend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "nest build",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:prod": "node dist/main"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}"# },
            FileDef { path: "tsconfig.json", content: r#"{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}"# },
            FileDef { path: "nest-cli.json", content: r#"$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src"
}"# },
            FileDef { path: "src/main.ts", content: "import { NestFactory } from '@nestjs/core';\nimport { AppModule } from './app.module';\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  await app.listen(3000);\n}\nbootstrap();\n" },
            FileDef { path: "src/app.module.ts", content: "import { Module } from '@nestjs/common';\n\n@Module({\n  imports: [],\n  controllers: [],\n  providers: [],\n})\nexport class AppModule {}\n" },
        ],
        init_command: "npm init -y",
        install_command: "npm install",
    },
    StackOption {
        id: "go-gin",
        name: "Go (Gin)",
        folders: &["src/controllers/", "src/services/", "src/repositories/", "src/middleware/", "src/routes/"],
        files: &[
            FileDef { path: "go.mod", content: "module backend\n\ngo 1.21\n\nrequire (\n\tgithub.com/gin-gonic/gin v1.9.1\n)\n" },
            FileDef { path: "main.go", content: "package main\n\nimport (\n\t\"github.com/gin-gonic/gin\"\n)\n\nfunc main() {\n\tr := gin.Default()\n\tr.GET(\"/\", func(c *gin.Context) {\n\t\tc.JSON(200, gin.H{\n\t\t\t\"message\": \"Hello World\",\n\t\t})\n\t})\n\tr.Run()\n}\n" },
        ],
        init_command: "go mod init backend",
        install_command: "go mod tidy",
    },
    StackOption {
        id: "spring-boot",
        name: "Spring Boot",
        folders: &["src/main/java/controllers/", "src/main/java/services/", "src/main/java/repositories/", "src/main/java/middleware/", "src/main/java/models/"],
        files: &[
            FileDef { path: "pom.xml", content: r#"<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>backend</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>backend</name>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
</project>"# },
            FileDef { path: "src/main/java/Application.java", content: "package com.example.backend;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) {\n        SpringApplication.run(Application.class, args);\n    }\n}\n" },
        ],
        init_command: "",
        install_command: "mvn install",
    },
    StackOption {
        id: "laravel",
        name: "Laravel",
        folders: &["app/Http/Controllers/", "app/Services/", "app/Repositories/", "app/Http/Middleware/", "routes/"],
        files: &[
            FileDef { path: "composer.json", content: r#"{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "require": {
        "php": "^8.1",
        "laravel/framework": "^10.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    }
}"# },
            FileDef { path: "artisan", content: "#!/usr/bin/env php\n<?php\n\nuse Symfony\\Component\\Console\\Input\\ArgvInput;\n\ndefine('LARAVEL_START', microtime(true));\n\nrequire __DIR__.'/vendor/autoload.php';\n\n$status = (require __DIR__.'/bootstrap/app.php')\n    ->handle(new ArgvInput());\n\nexit($status);\n" },
        ],
        init_command: "",
        install_command: "composer install",
    },
    StackOption {
        id: "none",
        name: "None",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
];

pub const DATABASE_STACKS: &[StackOption] = &[
    StackOption {
        id: "postgresql",
        name: "PostgreSQL",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
    StackOption {
        id: "mysql",
        name: "MySQL",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
    StackOption {
        id: "none",
        name: "None",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
];

pub fn get_frontend_folders(id: &str) -> Option<&'static [&'static str]> {
    FRONTEND_STACKS.iter().find(|s| s.id == id).map(|s| s.folders)
}

pub fn get_backend_folders(id: &str) -> Option<&'static [&'static str]> {
    BACKEND_STACKS.iter().find(|s| s.id == id).map(|s| s.folders)
}

pub fn get_frontend_files(id: &str) -> Option<&'static [FileDef]> {
    FRONTEND_STACKS.iter().find(|s| s.id == id).map(|s| s.files)
}

pub fn get_backend_files(id: &str) -> Option<&'static [FileDef]> {
    BACKEND_STACKS.iter().find(|s| s.id == id).map(|s| s.files)
}

pub fn get_frontend_init_command(id: &str) -> &'static str {
    FRONTEND_STACKS.iter().find(|s| s.id == id).map(|s| s.init_command).unwrap_or("")
}

pub fn get_frontend_install_command(id: &str) -> &'static str {
    FRONTEND_STACKS.iter().find(|s| s.id == id).map(|s| s.install_command).unwrap_or("")
}

pub fn get_backend_init_command(id: &str) -> &'static str {
    BACKEND_STACKS.iter().find(|s| s.id == id).map(|s| s.init_command).unwrap_or("")
}

pub fn get_backend_install_command(id: &str) -> &'static str {
    BACKEND_STACKS.iter().find(|s| s.id == id).map(|s| s.install_command).unwrap_or("")
}

pub fn get_database_url(id: &str) -> &'static str {
    match id {
        "postgresql" => "postgresql://user:password@localhost:5432/mydb",
        "mysql" => "mysql://user:password@localhost:3306/mydb",
        _ => "",
    }
}

pub fn validate_selection(frontend: &str, backend: &str) -> Result<(), &'static str> {
    if frontend == "none" && backend == "none" {
        return Err("Pilih minimal Frontend atau Backend");
    }
    Ok(())
}
