#[derive(Debug, PartialEq)]
pub struct StackOption {
    pub id: &'static str,
    pub name: &'static str,
    pub folders: &'static [&'static str],
    pub files: &'static [FileDef],
    pub init_command: &'static str,
    pub install_command: &'static str,
}

#[derive(Debug, PartialEq)]
pub struct FileDef {
    pub path: &'static str,
    pub content: &'static str,
}

pub const FRONTEND_STACKS: &[StackOption] = &[
    StackOption {
        id: "nextjs",
        name: "Next.js",
        folders: &[
            "src/components/ui/",
            "src/components/layout/",
            "src/app/",
            "src/hooks/",
            "src/lib/",
        ],
        files: &[
            FileDef {
                path: "package.json",
                content: r#"{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "typescript": "^5.0.0"
  }
}"#,
            },
            FileDef {
                path: "tsconfig.json",
                content: r#"{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}"#,
            },
            FileDef {
                path: "next-env.d.ts",
                content: r#"/// <reference types="next" />
/// <reference types="next/image-types/global" />
"#,
            },
            FileDef {
                path: "next.config.js",
                content: "const nextConfig = {};\n\nmodule.exports = nextConfig;\n",
            },
            FileDef {
                path: "src/app/layout.tsx",
                content: "import type { ReactNode } from 'react';\n\nexport const metadata = {\n  title: 'App',\n  description: 'Generated by SNIPE-CODE CLI',\n};\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n",
            },
            FileDef {
                path: "src/app/page.tsx",
                content: "export default function Home() {\n  return <main><h1>Welcome</h1></main>;\n}\n",
            },
        ],
        init_command: "",
        install_command: "npm install",
    },
    StackOption {
        id: "react-vite",
        name: "React (Vite)",
        folders: &[
            "src/components/ui/",
            "src/components/layout/",
            "src/pages/",
            "src/hooks/",
            "src/lib/",
        ],
        files: &[
            FileDef {
                path: "package.json",
                content: r#"{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^4.0.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.0"
  }
}"#,
            },
            FileDef {
                path: "index.html",
                content: "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>React App</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>\n",
            },
            FileDef {
                path: "vite.config.ts",
                content: "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n",
            },
            FileDef {
                path: "tsconfig.json",
                content: r#"{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}"#,
            },
            FileDef {
                path: "src/vite-env.d.ts",
                content: "/// <reference types=\"vite/client\" />\n",
            },
            FileDef {
                path: "src/App.tsx",
                content: "function App() {\n  return <div><h1>Welcome</h1></div>;\n}\n\nexport default App;\n",
            },
            FileDef {
                path: "src/main.tsx",
                content: "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n",
            },
        ],
        init_command: "",
        install_command: "npm install",
    },
    StackOption {
        id: "vue",
        name: "Vue",
        folders: &[
            "src/components/ui/",
            "src/components/layout/",
            "src/views/",
            "src/composables/",
            "src/lib/",
        ],
        files: &[
            FileDef {
                path: "package.json",
                content: r#"{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.0",
    "vue-tsc": "^2.0.0"
  }
}"#,
            },
            FileDef {
                path: "index.html",
                content: "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Vue App</title>\n  </head>\n  <body>\n    <div id=\"app\"></div>\n    <script type=\"module\" src=\"/src/main.ts\"></script>\n  </body>\n</html>\n",
            },
            FileDef {
                path: "vite.config.ts",
                content: "import { defineConfig } from 'vite';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({\n  plugins: [vue()],\n});\n",
            },
            FileDef {
                path: "tsconfig.json",
                content: r#"{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
  "references": [{ "path": "./tsconfig.node.json" }]
}"#,
            },
            FileDef {
                path: "tsconfig.node.json",
                content: r#"{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}"#,
            },
            FileDef {
                path: "src/App.vue",
                content: "<script setup lang=\"ts\">\n</script>\n\n<template>\n  <div>\n    <h1>Welcome</h1>\n  </div>\n</template>\n",
            },
            FileDef {
                path: "src/main.ts",
                content: "import { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).mount('#app');\n",
            },
        ],
        init_command: "",
        install_command: "npm install",
    },
    StackOption {
        id: "nuxtjs",
        name: "Nuxt.js",
        folders: &[
            "components/ui/",
            "components/layout/",
            "pages/",
            "composables/",
            "utils/",
        ],
        files: &[
            FileDef {
                path: "package.json",
                content: r#"{
  "name": "frontend",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.10.0",
    "vue": "^3.4.0",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0"
  }
}"#,
            },
            FileDef {
                path: "nuxt.config.ts",
                content: "export default defineNuxtConfig({\n  devtools: { enabled: false },\n});\n",
            },
            FileDef {
                path: "tsconfig.json",
                content: r#"{
  "extends": "./.nuxt/tsconfig.json"
}"#,
            },
            FileDef {
                path: "app.vue",
                content: "<template>\n  <div>\n    <NuxtPage />\n  </div>\n</template>\n",
            },
            FileDef {
                path: "pages/index.vue",
                content: "<script setup lang=\"ts\">\n</script>\n\n<template>\n  <div>\n    <h1>Welcome</h1>\n  </div>\n</template>\n",
            },
        ],
        init_command: "",
        install_command: "npm install",
    },
    StackOption {
        id: "none",
        name: "None",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
];

pub const BACKEND_STACKS: &[StackOption] = &[
    StackOption {
        id: "dotnet8",
        name: ".NET 8",
        folders: &[
            "Controllers/",
            "Services/",
            "Repositories/",
            "Middleware/",
            "Models/",
        ],
        files: &[
            FileDef {
                path: "app.csproj",
                content: r#"<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>"#,
            },
            FileDef {
                path: "Program.cs",
                content: "var builder = WebApplication.CreateBuilder(args);\n\nbuilder.Services.AddControllers();\n\nvar app = builder.Build();\n\napp.MapControllers();\napp.MapGet(\"/\", () => \"SNIPE-CODE\");\n\napp.Run(\"http://0.0.0.0:5000\");\n",
            },
        ],
        init_command: "",
        install_command: "dotnet restore",
    },
    StackOption {
        id: "nestjs",
        name: "NestJS",
        folders: &[
            "src/controllers/",
            "src/services/",
            "src/repositories/",
            "src/middleware/",
            "src/routes/",
        ],
        files: &[
            FileDef {
                path: "package.json",
                content: r#"{
  "name": "backend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "nest build",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:prod": "node dist/main.js"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}"#,
            },
            FileDef {
                path: "tsconfig.json",
                content: r#"{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "strictBindCallApply": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true
  }
}"#,
            },
            FileDef {
                path: "tsconfig.build.json",
                content: r#"{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "dist", "test", "**/*spec.ts"]
}"#,
            },
            FileDef {
                path: "nest-cli.json",
                content: r#"{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src"
}"#,
            },
            FileDef {
                path: "src/main.ts",
                content: "import 'reflect-metadata';\nimport { NestFactory } from '@nestjs/core';\nimport { AppModule } from './app.module';\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  const port = Number(process.env.PORT ?? 3000);\n  await app.listen(port, '0.0.0.0');\n}\n\nvoid bootstrap();\n",
            },
            FileDef {
                path: "src/app.module.ts",
                content: "import { Module } from '@nestjs/common';\n\n@Module({\n  imports: [],\n  controllers: [],\n  providers: [],\n})\nexport class AppModule {}\n",
            },
            FileDef {
                path: "Dockerfile",
                content: r#"FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY nest-cli.json tsconfig*.json ./
COPY src ./src
RUN npm run build && npm prune --omit=dev

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package.json ./
EXPOSE 3000
CMD ["node", "dist/main.js"]
"#,
            },
        ],
        init_command: "",
        install_command: "npm install",
    },
    StackOption {
        id: "go-gin",
        name: "Go (Gin)",
        folders: &[
            "src/controllers/",
            "src/services/",
            "src/repositories/",
            "src/middleware/",
            "src/routes/",
        ],
        files: &[
            FileDef {
                path: "go.mod",
                content: "module backend\n\ngo 1.21\n\nrequire github.com/gin-gonic/gin v1.9.1\n",
            },
            FileDef {
                path: "main.go",
                content: "package main\n\nimport (\n\t\"log\"\n\t\"net/http\"\n\n\t\"github.com/gin-gonic/gin\"\n)\n\nfunc main() {\n\tr := gin.Default()\n\tr.GET(\"/\", func(c *gin.Context) {\n\t\tc.JSON(http.StatusOK, gin.H{\"message\": \"Hello World\"})\n\t})\n\n\tif err := r.Run(\":8080\"); err != nil {\n\t\tlog.Fatal(err)\n\t}\n}\n",
            },
        ],
        init_command: "",
        install_command: "go mod download",
    },
    StackOption {
        id: "spring-boot",
        name: "Spring Boot",
        folders: &[
            "src/main/java/com/example/backend/",
            "src/main/java/com/example/backend/controllers/",
            "src/main/java/com/example/backend/services/",
            "src/main/java/com/example/backend/repositories/",
            "src/main/java/com/example/backend/middleware/",
            "src/main/java/com/example/backend/models/",
            "src/main/resources/",
            "src/test/java/com/example/backend/",
        ],
        files: &[
            FileDef {
                path: "pom.xml",
                content: r#"<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
        <relativePath/>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>backend</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>backend</name>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>"#,
            },
            FileDef {
                path: "src/main/java/com/example/backend/Application.java",
                content: "package com.example.backend;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) {\n        SpringApplication.run(Application.class, args);\n    }\n}\n",
            },
            FileDef {
                path: "src/test/java/com/example/backend/ApplicationTests.java",
                content: "package com.example.backend;\n\nimport org.junit.jupiter.api.Test;\n\nimport static org.junit.jupiter.api.Assertions.assertTrue;\n\nclass ApplicationTests {\n    @Test\n    void applicationTest() {\n        assertTrue(true);\n    }\n}\n",
            },
        ],
        init_command: "",
        install_command: "mvn test",
    },
    StackOption {
        id: "laravel",
        name: "Laravel",
        folders: &[
            "app/Console/",
            "app/Exceptions/",
            "app/Http/Controllers/",
            "app/Http/Middleware/",
            "app/Models/",
            "app/Providers/",
            "app/Repositories/",
            "app/Services/",
            "bootstrap/cache/",
            "config/",
            "database/",
            "public/",
            "routes/",
            "storage/app/",
            "storage/framework/cache/data/",
            "storage/framework/sessions/",
            "storage/framework/testing/",
            "storage/framework/views/",
            "storage/logs/",
            "tests/Feature/",
        ],
        files: &[
            FileDef {
                path: "composer.json",
                content: r#"{
    "name": "laravel/laravel",
    "type": "project",
    "description": "Laravel 10 application.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "laravel/framework": "^10.10"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "test": [
            "@php artisan test"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}"#,
            },
            FileDef {
                path: "artisan",
                content: "#!/usr/bin/env php\n<?php\n\nuse Illuminate\\Contracts\\Console\\Kernel;\nuse Symfony\\Component\\Console\\Input\\ArgvInput;\nuse Symfony\\Component\\Console\\Output\\ConsoleOutput;\n\ndefine('LARAVEL_START', microtime(true));\n\nrequire __DIR__.'/vendor/autoload.php';\n\n$app = require_once __DIR__.'/bootstrap/app.php';\n\n$kernel = $app->make(Kernel::class);\n\n$status = $kernel->handle(\n    $input = new ArgvInput,\n    new ConsoleOutput\n);\n\n$kernel->terminate($input, $status);\n\nexit($status);\n",
            },
            FileDef {
                path: "bootstrap/app.php",
                content: r#"<?php

$app = new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

return $app;
"#,
            },
            FileDef {
                path: "app/Console/Kernel.php",
                content: r#"<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    protected $commands = [];

    protected function schedule(Schedule $schedule): void
    {
    }

    protected function commands(): void
    {
    }
}
"#,
            },
            FileDef {
                path: "app/Exceptions/Handler.php",
                content: r#"<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    public function register(): void
    {
    }
}
"#,
            },
            FileDef {
                path: "app/Http/Kernel.php",
                content: r#"<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    protected $middleware = [];

    protected $middlewareGroups = [
        'web' => [
            \Illuminate\Cookie\Middleware\EncryptCookies::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'api' => [
            \Illuminate\Routing\Middleware\ThrottleRequests::class.':api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];

    protected $middlewareAliases = [
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
}
"#,
            },
            FileDef {
                path: "app/Providers/AppServiceProvider.php",
                content: r#"<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
    }

    public function boot(): void
    {
    }
}
"#,
            },
            FileDef {
                path: "app/Providers/RouteServiceProvider.php",
                content: r#"<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    public const HOME = '/home';

    public function boot(): void
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::middleware('api')
                ->prefix('api')
                ->group(base_path('routes/api.php'));
            Route::middleware('web')
                ->group(base_path('routes/web.php'));
        });
    }

    protected function configureRateLimiting(): void
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });
    }
}
"#,
            },
            FileDef {
                path: "app/Models/User.php",
                content: r#"<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
}
"#,
            },
            FileDef {
                path: "config/app.php",
                content: r#"<?php

use Illuminate\Support\Facades\Facade;
use Illuminate\Support\ServiceProvider;

return [
    'name' => env('APP_NAME', 'Laravel'),
    'env' => env('APP_ENV', 'production'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost'),
    'asset_url' => env('ASSET_URL'),
    'timezone' => 'UTC',
    'locale' => 'en',
    'fallback_locale' => 'en',
    'faker_locale' => 'en_US',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
    'maintenance' => [
        'driver' => 'file',
    ],
    'providers' => ServiceProvider::defaultProviders()->merge([
        App\Providers\AppServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
    ])->toArray(),
    'aliases' => Facade::defaultAliases()->toArray(),
];
"#,
            },
            FileDef {
                path: "config/auth.php",
                content: r#"<?php

return [
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
    ],
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_reset_tokens',
            'expire' => 60,
            'throttle' => 60,
        ],
    ],
    'password_timeout' => 10800,
];
"#,
            },
            FileDef {
                path: "config/broadcasting.php",
                content: r#"<?php

return [
    'default' => env('BROADCAST_DRIVER', 'null'),
    'connections' => [],
];
"#,
            },
            FileDef {
                path: "config/cache.php",
                content: r#"<?php

use Illuminate\Support\Str;

return [
    'default' => env('CACHE_DRIVER', 'file'),
    'stores' => [
        'array' => [
            'driver' => 'array',
            'serialize' => false,
        ],
        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],
        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => null,
            'lock_connection' => null,
        ],
    ],
    'prefix' => env('CACHE_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_cache_'),
];
"#,
            },
            FileDef {
                path: "config/cors.php",
                content: r#"<?php

return [
    'paths' => [],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => false,
];
"#,
            },
            FileDef {
                path: "config/database.php",
                content: r#"<?php

use Illuminate\Support\Str;

return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
        ],
        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],
        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],
    ],
    'migrations' => 'migrations',
    'redis' => [
        'client' => env('REDIS_CLIENT', 'phpredis'),
        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],
        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],
    ],
];
"#,
            },
            FileDef {
                path: "config/filesystems.php",
                content: r#"<?php

return [
    'default' => env('FILESYSTEM_DISK', 'local'),
    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'throw' => false,
        ],
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
            'throw' => false,
        ],
    ],
    'links' => [
        public_path('storage') => storage_path('app/public'),
    ],
];
"#,
            },
            FileDef {
                path: "config/hashing.php",
                content: r#"<?php

return [
    'driver' => 'bcrypt',
    'bcrypt' => [
        'rounds' => env('BCRYPT_ROUNDS', 12),
    ],
    'argon' => [
        'memory' => 65536,
        'threads' => 1,
        'time' => 4,
    ],
];
"#,
            },
            FileDef {
                path: "config/logging.php",
                content: r#"<?php

use Monolog\Handler\StreamHandler;

return [
    'default' => env('LOG_CHANNEL', 'stack'),
    'deprecations' => [
        'channel' => env('LOG_DEPRECATIONS_CHANNEL', 'null'),
        'trace' => false,
    ],
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single'],
            'ignore_exceptions' => false,
        ],
        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => env('LOG_LEVEL', 'debug'),
            'replace_placeholders' => true,
        ],
        'daily' => [
            'driver' => 'daily',
            'path' => storage_path('logs/laravel.log'),
            'level' => env('LOG_LEVEL', 'debug'),
            'days' => 14,
            'replace_placeholders' => true,
        ],
        'stderr' => [
            'driver' => 'monolog',
            'level' => env('LOG_LEVEL', 'debug'),
            'handler' => StreamHandler::class,
            'formatter' => env('LOG_STDERR_FORMATTER'),
            'with' => [
                'stream' => 'php://stderr',
            ],
        ],
        'null' => [
            'driver' => 'monolog',
            'handler' => StreamHandler::class,
            'with' => [
                'stream' => 'php://memory',
            ],
        ],
    ],
];
"#,
            },
            FileDef {
                path: "config/mail.php",
                content: r#"<?php

return [
    'default' => env('MAIL_MAILER', 'log'),
    'mailers' => [
        'smtp' => [
            'transport' => 'smtp',
            'host' => env('MAIL_HOST', '127.0.0.1'),
            'port' => env('MAIL_PORT', 2525),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
        ],
        'log' => [
            'transport' => 'log',
            'channel' => env('MAIL_LOG_CHANNEL'),
        ],
    ],
    'from' => [
        'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
        'name' => env('MAIL_FROM_NAME', 'Laravel'),
    ],
];
"#,
            },
            FileDef {
                path: "config/queue.php",
                content: r#"<?php

return [
    'default' => env('QUEUE_CONNECTION', 'sync'),
    'connections' => [
        'sync' => [
            'driver' => 'sync',
        ],
        'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
            'after_commit' => false,
        ],
    ],
    'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],
];
"#,
            },
            FileDef {
                path: "config/services.php",
                content: r#"<?php

return [];
"#,
            },
            FileDef {
                path: "config/session.php",
                content: r#"<?php

use Illuminate\Support\Str;

return [
    'driver' => env('SESSION_DRIVER', 'file'),
    'lifetime' => env('SESSION_LIFETIME', 120),
    'expire_on_close' => false,
    'encrypt' => false,
    'files' => storage_path('framework/sessions'),
    'connection' => env('SESSION_CONNECTION'),
    'table' => 'sessions',
    'store' => env('SESSION_STORE'),
    'lottery' => [2, 100],
    'cookie' => env('SESSION_COOKIE', Str::slug(env('APP_NAME', 'laravel'), '_').'_session'),
    'path' => '/',
    'domain' => env('SESSION_DOMAIN'),
    'secure' => env('SESSION_SECURE_COOKIE'),
    'http_only' => true,
    'same_site' => 'lax',
];
"#,
            },
            FileDef {
                path: "config/view.php",
                content: r#"<?php

return [
    'paths' => [
        resource_path('views'),
    ],
    'compiled' => env('VIEW_COMPILED_PATH', realpath(storage_path('framework/views'))),
];
"#,
            },
            FileDef {
                path: "public/index.php",
                content: r#"<?php

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

if (file_exists($maintenance = __DIR__.'/../storage/framework/maintenance.php')) {
    require $maintenance;
}

require __DIR__.'/../vendor/autoload.php';

$app = require_once __DIR__.'/../bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$response = $kernel->handle(
    $request = Request::capture()
)->send();

$kernel->terminate($request, $response);
"#,
            },
            FileDef {
                path: "routes/api.php",
                content: "<?php\n\nuse Illuminate\\Support\\Facades\\Route;\n\nRoute::get('/ping', function () {\n    return ['message' => 'pong'];\n});\n",
            },
            FileDef {
                path: "routes/web.php",
                content: "<?php\n\nuse Illuminate\\Support\\Facades\\Route;\n\nRoute::get('/', function () {\n    return response('SNIPE-CODE');\n});\n",
            },
            FileDef {
                path: "tests/TestCase.php",
                content: r#"<?php

namespace Tests;

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }
}
"#,
            },
            FileDef {
                path: "tests/Feature/ExampleTest.php",
                content: r#"<?php

namespace Tests\Feature;

use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
"#,
            },
            FileDef {
                path: "phpunit.xml",
                content: r#"<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true">
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory suffix=".php">app</directory>
        </include>
    </source>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="APP_KEY" value="base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="/>
        <env name="APP_DEBUG" value="true"/>
        <env name="APP_URL" value="http://localhost"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <env name="MAIL_MAILER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
    </php>
</phpunit>
"#,
            },
            FileDef {
                path: ".env.example",
                content: r#"APP_NAME=SNIPE-CODE
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost:8000

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=snipe_local
DB_USERNAME=snipe_local
DB_PASSWORD=CHANGE_ME_LOCAL_DB_PASSWORD

CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
"#,
            },
        ],
        init_command: "",
        install_command: "composer install",
    },
    StackOption {
        id: "none",
        name: "None",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
];

pub const DATABASE_STACKS: &[StackOption] = &[
    StackOption {
        id: "postgresql",
        name: "PostgreSQL",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
    StackOption {
        id: "mysql",
        name: "MySQL",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
    StackOption {
        id: "none",
        name: "None",
        folders: &[],
        files: &[],
        init_command: "",
        install_command: "",
    },
];

pub fn get_frontend_folders(id: &str) -> Option<&'static [&'static str]> {
    FRONTEND_STACKS
        .iter()
        .find(|s| s.id == id)
        .map(|s| s.folders)
}

pub fn get_backend_folders(id: &str) -> Option<&'static [&'static str]> {
    BACKEND_STACKS
        .iter()
        .find(|s| s.id == id)
        .map(|s| s.folders)
}

pub fn get_frontend_files(id: &str) -> Option<&'static [FileDef]> {
    FRONTEND_STACKS.iter().find(|s| s.id == id).map(|s| s.files)
}

pub fn get_backend_files(id: &str) -> Option<&'static [FileDef]> {
    BACKEND_STACKS.iter().find(|s| s.id == id).map(|s| s.files)
}

pub fn get_frontend_init_command(id: &str) -> &'static str {
    FRONTEND_STACKS
        .iter()
        .find(|s| s.id == id)
        .map(|s| s.init_command)
        .unwrap_or("")
}

pub fn get_frontend_install_command(id: &str) -> &'static str {
    FRONTEND_STACKS
        .iter()
        .find(|s| s.id == id)
        .map(|s| s.install_command)
        .unwrap_or("")
}

pub fn get_backend_init_command(id: &str) -> &'static str {
    BACKEND_STACKS
        .iter()
        .find(|s| s.id == id)
        .map(|s| s.init_command)
        .unwrap_or("")
}

pub fn get_backend_install_command(id: &str) -> &'static str {
    BACKEND_STACKS
        .iter()
        .find(|s| s.id == id)
        .map(|s| s.install_command)
        .unwrap_or("")
}

pub fn get_database_url(id: &str) -> &'static str {
    match id {
        "postgresql" => "postgresql://user:password@localhost:5432/mydb",
        "mysql" => "mysql://user:password@localhost:3306/mydb",
        _ => "",
    }
}

pub fn validate_selection(frontend: &str, backend: &str) -> Result<(), &'static str> {
    if frontend == "none" && backend == "none" {
        return Err("Pilih minimal Frontend atau Backend");
    }
    Ok(())
}
